# Generated by Django 3.1.5 on 2021-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210114_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
